name: laser_rl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.3
  - pip:
    - pybullet>=3.2.5
    - numpy>=1.20.0
    - gym==0.21.0
    - stable-baselines3==1.5.0
    - torch>=1.10.0
    - ray[rllib]==1.13.0
    - tensorboard>=2.8.0
    - matplotlib>=3.5.0
    - shimmy 